# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: watersensor.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='watersensor.proto',
  package='',
  serialized_pb='\n\x11watersensor.proto\"\\\n\x0bWaterSensor\x12\x12\n\ntime_stamp\x18\x01 \x02(\x05\x12\x13\n\x0bwater_level\x18\x02 \x01(\x02\x12\x13\n\x0btemperature\x18\x03 \x01(\x02\x12\x0f\n\x07\x62\x61ttery\x18\x04 \x01(\x05')




_WATERSENSOR = _descriptor.Descriptor(
  name='WaterSensor',
  full_name='WaterSensor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time_stamp', full_name='WaterSensor.time_stamp', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='water_level', full_name='WaterSensor.water_level', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='temperature', full_name='WaterSensor.temperature', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='battery', full_name='WaterSensor.battery', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=21,
  serialized_end=113,
)

DESCRIPTOR.message_types_by_name['WaterSensor'] = _WATERSENSOR

class WaterSensor(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _WATERSENSOR

  # @@protoc_insertion_point(class_scope:WaterSensor)


# @@protoc_insertion_point(module_scope)
