/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev at Wed Dec 27 10:35:23 2017. */

#include "levelsensor.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t WaterSensor_fields[5] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, WaterSensor, time_stamp, time_stamp, 0),
    PB_FIELD(  2, FLOAT   , OPTIONAL, STATIC  , OTHER, WaterSensor, water_level, time_stamp, 0),
    PB_FIELD(  3, FLOAT   , OPTIONAL, STATIC  , OTHER, WaterSensor, temperature, water_level, 0),
    PB_FIELD(  4, INT32   , OPTIONAL, STATIC  , OTHER, WaterSensor, battery, temperature, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
